services:
  ytdl:
    image: pknw1/ytdl-prod:v4
    env_file: .env
    container_name: ytdl
    hostname: ytdl
    networks:
      - proxy
    volumes:
      - ./config:/config
      - /media:/media
      - /dev/fuse:/dev/fuse
    environment:
      - VIRTUAL_HOST=yt.pknw1.co.uk
      - VIRTUAL_PORT=8080
      - APP_GROUP=Core
      - APP_LOGO=https://static-00.iconduck.com/assets.00/portainer-icon-1465x2048-t155ekm0.png
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 200M

networks:
  proxy:
    external: true
